# Warning please use virtual env if dont have fun errors

# Install required dependencies

In [1]:
!pip install tensorflow opencv-python mediapipe scikit-learn matplotlib 

Defaulting to user installation because normal site-packages is not writeable


# Importing the dependecies

In [2]:
import cv2 # type: ignore
import numpy as np # type: ignore
import os 
from matplotlib import pyplot as plt # type: ignore
import time
import mediapipe as mp # type: ignore

2024-09-19 20:51:47.976961: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-19 20:51:48.025084: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-19 20:51:48.119096: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-19 20:51:48.254113: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-19 20:51:48.279526: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-19 20:51:48.415448: I tensorflow/core/platform/cpu_feature_gu

# Keypoints using MP Holistic

In [3]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [4]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [5]:
def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION) # Draw face connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [6]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             )

In [7]:
cap = cv2.VideoCapture(0)
# Set media pipe model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        
        # Read feed
        ret, frame = cap.read()
        
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        
        # Draw landmarks
        # draw_landmarks(image, results)
        draw_styled_landmarks(image, results)
        
        # Show to screen
        cv2.imshow('Sign language detection', image)
        
        # Terminate program
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

I0000 00:00:1726759370.756019   83535 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1726759370.771382   83734 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1~22.04.2), renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1726759371.134326   83726 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726759371.216848   83725 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726759371.220618   83724 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726759371.225314   83726 inference_feedback_manager.cc:114] Feedback manager requires a model with a sing

# Extract Keypoints values

In [8]:
len(results.pose_landmarks.landmark)

33

In [9]:

pose = []
for res in results.pose_landmarks.landmark:
    test = np.array([res.x, res.y, res.z, res.visibility])
    pose.append(test) 

In [10]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
left_hand = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21 * 3)
right_hand = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21 * 3)

In [11]:
pose.shape, left_hand.shape, right_hand.shape

((132,), (63,), (63,))

In [45]:
pose

array([ 5.38359344e-01,  3.39714497e-01, -8.95556927e-01,  9.99946833e-01,
        5.63827574e-01,  2.64041573e-01, -8.14892769e-01,  9.99904335e-01,
        5.80285728e-01,  2.62579173e-01, -8.14602971e-01,  9.99908805e-01,
        5.96130490e-01,  2.62194306e-01, -8.13925147e-01,  9.99895096e-01,
        5.06263077e-01,  2.74577737e-01, -8.34044814e-01,  9.99907374e-01,
        4.83849823e-01,  2.80554622e-01, -8.32928181e-01,  9.99907553e-01,
        4.63007987e-01,  2.87505627e-01, -8.33535016e-01,  9.99904752e-01,
        6.18046761e-01,  2.95175850e-01, -3.70785773e-01,  9.99917626e-01,
        4.35310781e-01,  3.17920327e-01, -4.49173778e-01,  9.99949217e-01,
        5.72513223e-01,  4.25408006e-01, -7.39091516e-01,  9.99959111e-01,
        5.05310297e-01,  4.34960783e-01, -7.64142096e-01,  9.99967337e-01,
        7.79115081e-01,  6.84736073e-01, -1.97872207e-01,  9.99804854e-01,
        2.78946221e-01,  6.76627040e-01, -2.58307129e-01,  9.99178529e-01,
        1.05548644e+00,  

In [46]:
face

array([ 0.54238755,  0.41056949, -0.03195506, ...,  0.6242131 ,
        0.25411949,  0.02413429])

In [39]:
left_hand

array([ 8.85786533e-01,  6.02120161e-01,  4.36515194e-07,  8.02830935e-01,
        5.84703743e-01, -2.62328256e-02,  7.30945885e-01,  5.29658794e-01,
       -3.95872183e-02,  6.79946184e-01,  4.85104322e-01, -5.16660623e-02,
        6.35198176e-01,  4.56421852e-01, -6.41095415e-02,  7.74031699e-01,
        3.66275847e-01, -1.73795354e-02,  7.39424884e-01,  2.74845839e-01,
       -3.41628343e-02,  7.16493249e-01,  2.20903933e-01, -5.03450930e-02,
        6.96576715e-01,  1.74304947e-01, -6.37653768e-02,  8.21716547e-01,
        3.42696398e-01, -2.40348335e-02,  7.99062967e-01,  2.27308407e-01,
       -3.67263705e-02,  7.84149051e-01,  1.55497000e-01, -5.18586710e-02,
        7.71376908e-01,  9.69935656e-02, -6.45048022e-02,  8.71346951e-01,
        3.45809668e-01, -3.55069600e-02,  8.61825764e-01,  2.32723042e-01,
       -5.43356091e-02,  8.54586959e-01,  1.62459061e-01, -7.08596259e-02,
        8.45148981e-01,  9.88062322e-02, -8.36738274e-02,  9.21588778e-01,
        3.68705213e-01, -

In [40]:
right_hand

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

If the landmark is not found

In [12]:
np.zeros(21*3).shape

(63,)

In [13]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33 * 4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468 * 3)
    left_hand = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21 * 3)
    right_hand = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21 * 3)
    
    return np.concatenate([pose, face, left_hand, right_hand])

In [14]:
result_test = extract_keypoints(results)

In [15]:
result_test

array([ 0.62423933,  0.49259046, -0.8905651 , ...,  0.47020593,
        0.09855881, -0.05278813])

In [16]:
468 * 3 + 33 * 4 + 2 *(21 * 3)

1662

In [17]:
np.save('0', result_test)

In [18]:
np.load('0.npy')

array([ 0.62423933,  0.49259046, -0.8905651 , ...,  0.47020593,
        0.09855881, -0.05278813])

# Setup Folders for Collection Data set

In [19]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('Dataset')

# Actions that we try to detect
actions = np.array(['hello', 'thank you', 'good', 'afternoon'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequences_length = 30

In [20]:
# Creating a folder for each action like : hello, thank you, good, afternoon

for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

# Collecting Keypoints values for training and testing

In [67]:
cap = cv2.VideoCapture(0)
# Set media pipe model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequences_length):
                # Read feed
                ret, frame = cap.read()
                
                # Make detections
                image, results = mediapipe_detection(frame, holistic)
                
                # Draw landmarks
                # draw_landmarks(image, results)
                draw_styled_landmarks(image, results)
                
                # Apply collection wait logic
                if frame_num == 0:
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 1, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    
                    # Show to screen
                    cv2.imshow('Sign language detection', image)
                    cv2.waitKey(2000) #! 2 seconds wait time (changeable for the higher sign language moments)
                else:
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('Sign language detection', image)
                    
                # Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)
                
        
                # Terminate program
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                
cap.release()
cv2.destroyAllWindows()

I0000 00:00:1726294994.461728  135093 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1726294994.471414  138913 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1~22.04.2), renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
W0000 00:00:1726294994.726144  138908 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726294994.788216  138908 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726294994.791665  138907 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726294994.792324  138909 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback t

# Preprocess Data and Create Lables and Features

In [21]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [22]:
label_map = {label:num for num, label in enumerate(actions)}

In [23]:
label_map

{'hello': 0, 'thank you': 1, 'good': 2, 'afternoon': 3}

### Labeling the image

In [24]:
sequences, labels = [], []
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequences_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [25]:
np.array(sequences).shape

(120, 30, 1662)

In [26]:
np.array(labels).shape

(120,)

In [27]:
X = np.array(sequences)

In [28]:
X.shape

(120, 30, 1662)

In [29]:
y = to_categorical(labels).astype(int)

In [30]:
y

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1,

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [32]:
y_test.shape

(6, 4)

# Build and Train LSTM Neural Network

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [34]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir) 

In [35]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='tanh', input_shape=(30, 1662))) # Match input shape
model.add(LSTM(128, return_sequences=True, activation='tanh'))
model.add(LSTM(64, return_sequences=False, activation='tanh'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))  # Number of actions

/home/vaibhav/.local/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [36]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [38]:
model.fit(X_train, y_train, epochs=150, callbacks=[tb_callback])

Epoch 1/150


2024-09-19 20:57:22.136850: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 22736160 exceeds 10% of free system memory.


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - categorical_accuracy: 0.7478 - loss: 0.3355
Epoch 2/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 160ms/step - categorical_accuracy: 0.7882 - loss: 0.3406
Epoch 3/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - categorical_accuracy: 0.7465 - loss: 0.3653
Epoch 4/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - categorical_accuracy: 0.7840 - loss: 0.3383
Epoch 5/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 124ms/step - categorical_accuracy: 0.7628 - loss: 0.3283
Epoch 6/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - categorical_accuracy: 0.7389 - loss: 0.3398
Epoch 7/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 201ms/step - categorical_accuracy: 0.7399 - loss: 0.3520
Epoch 8/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 120ms/step - categorical_accuracy: 0.7972 - loss: 0.3229
Epoch 9/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - categorical_accuracy: 0.7497 - loss: 0.3358
Epoch 10/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - categorical_accuracy: 0.7064 - loss: 0.7959
Epoch 11/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 

In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30, 64)         │       442,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 30, 128)        │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 4)              │           132 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,790,126 (6.83 MB)

 Trainable params: 596,708 (2.28 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,193,418 (4.55 MB)

# Make Predictions

In [40]:
res = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 849ms/step


In [41]:
actions[np.argmax(res[4])]

'hello'

In [42]:
actions[np.argmax(y_test[4])]

'hello'

# Save Weights

In [43]:
model.save('sign_language_model.h5')

In [44]:
model.load_weights('sign_language_model.h5')

# Evaluation using Confusion Matrix and Accuracy

In [45]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [46]:
yhat = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


In [47]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [48]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[4, 0],
        [0, 2]],

       [[4, 0],
        [0, 2]],

       [[5, 0],
        [0, 1]],

       [[5, 0],
        [0, 1]]])

In [49]:
accuracy_score(ytrue, yhat)

1.0

# Test in Real Time

In [50]:
# Detection variables
sequence = []
sentence = []
predictions = []
threshold = 0.8     #! Threshold for prediction probability (How much model is sure about the prediction)

cap = cv2.VideoCapture(0)
# Set media pipe model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        
        # Read feed
        ret, frame = cap.read()
        
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        
        # Draw landmarks
        # draw_landmarks(image, results)
        draw_styled_landmarks(image, results)
        
        # Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            predictions.append(np.argmax(res))
            
        # Screen logic
            if np.unique(predictions[-10:])[0] == np.argmax(res): 
                if res[np.argmax(res)] > threshold: 
                    if len(sentence) > 0: 
                        if actions[np.argmax(res)] != sentence[-1]:
                            sentence.append(actions[np.argmax(res)])
                    else:
                        sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]
            
            cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
            cv2.putText(image, ' '.join(sentence), (3,30), 
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)        
        
        # Show to screen
        cv2.imshow('Sign language detection', image)
        
        # Terminate program
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

I0000 00:00:1726759791.362006   83535 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1726759791.370008   87364 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1~22.04.2), renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
W0000 00:00:1726759791.667743   87358 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726759791.757903   87358 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726759791.764240   87359 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726759791.765565   87360 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback t

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 694ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
hello
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
good
1